"use strict";
// let fruit = "apple";
// console.log(fruit == "apple");
// console.log(fruit !== "apple");
// let Uppercasefruit= "APPLE";
// console.log(Uppercasefruit.toLowerCase() == fruit);
// let uppercasefruit= "APPLE";
// console.log(uppercasefruit.toLowerCase() !== fruit);
// let num1 = 10;
// let num2 = 20;
// console.log(num1 == num2);
// console.log(num1 !== num2);
// console.log(num2 < num1);
// console.log(num2 > num1);
// console.log(num2 >= num1);
// console.log(num2 <= num1);
// console.log(num2 !== num1  &&  num2 > num1);
// console.log(num1 < num2 && num1 == num2);
// console.log(num2 > num1 ||  num1 !== num2);
// console.log(num1 > num2 || num1 == num2);
let fruits = ["Apple", "Orange", "Mango"];
console.log(fruits.includes("Mango"));
console.log(!fruits.includes("Mango"));
